### ISSUE TITLE
isPanelVisible is not a function

### ISSUE THREAD

**Issue by morganics** [NatelEnergy/grafana-plotly-panel#5]
I'm working with v4.3 pre-1 of Grafana (just as a heads up) and I'm getting the error 'isPanelVisible' is not a function. I'm not sure whether this is an error with the plotly panel or not, as other graphs work fine, but just to make you aware before it happens! When I checkout an earlier working copy, the plotly panel is ok.

**Comment by ryantxu** [comment]
I just pushed a fix for this :)

if you checkout directly, i is fixed, otherwise wait (likely tomorrow?) for this to get applied:
https://github.com/grafana/grafana-plugin-repository/pull/110

**Comment by ryantxu** [comment]
should be solved in latest release.
